### ISSUE TITLE
Unable to upload wasm files on terra-station

### ISSUE THREAD

**Issue by 0xkdavid** [CosmWasm/cw-tokens#12]
`failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract has unknown interface_version_* marker export (see https://github.com/CosmWasm/cosmwasm/blob/main/packages/vm/README.md): store wasm contract failed: invalid request`

What branch version works with terra network?

**Comment by Odelya** [comment]
@0xkdavid I have the same issue - did you solve it?

**Comment by orkunkl** [comment]
Terra network version and contract version mismatches cause the error. you must deploy the right version
